### ISSUE TITLE
Email configuration needs work

### ISSUE THREAD

**Issue by tonyg** [racket/pkg-index#1]
The current code simply sends email from the machine the pkgd server is running on, assuming it is permitted to send mail from `...@racket-lang.org` addresses. This results in a lot of bounces because of reverse-DNS-lookup and so forth. We should switch it to send via some authorised racket-lang.org mail server.

**Comment by jeapostrophe** [comment]
I recall changing how this was set up earlier in the fall based on some feedback from an IRC user and it fixed his problem. I can't find the changes I made though. I believe it had something to do with forwarding through gmail with @racket-lang account

**Comment by tonyg** [comment]
I'll close this because I don't know a way of reproducing the problems -- and I don't even have any record of what the problems I was seeing were! Things seem OK with the current setup, at least for emails to my own personal domain. I'll try to make better bug reports in future. Sorry for the noise.
