### ISSUE TITLE
Use https for Documentation button and also pkg-build redirect

### ISSUE THREAD

**Issue by greghendershott** [racket/pkg-index#17]
1. Go to https://pkgs.racket-lang.org/package/sql
2. Click the `Documentation` button.
3. Its URL is http://pkg-build.racket-lang.org/doc/sql@sql/index.html (http not https)
4. That redirects to http://docs.racket-lang.org/sql/index.html (http not https)

It looks like there are two issues:

1. In step 3, preferably the URL should use http**s**: https://pkg-build.racket-lang.org/doc/sql@sql/index.html

2. To check if whether `pkg-build` is already set to accept SSL, I manually visited https://pkg-build.racket-lang.org/doc/sql@sql/index.html. The good news is, it works. The bad news is, the subsequent redirect to `docs` doesn't use SSL even though `docs` also would accept that.

**Comment by jeapostrophe** [comment]
I updated `pkg-index`. I think that `pkg-build` will redirect correctly only once we change the Cloudflare redirect rules. @mflatt --- I don't have access to our Cloudflare account, so I can't check this. Will you share it with me or take a look?

**Comment by SimonLSchlee** [comment]
It looks to me like this is fixed? Both urls show https for me.
