### ISSUE TITLE
[Feature request] add date_added to package metadata

### ISSUE THREAD

**Issue by spdegabrielle** [racket/pkg-index#19]
Hi,

[Feature request] add date_added to package metadata

I think this is the right file, but I'm a bit out of my depth: https://github.com/racket/pkg-index/blob/master/official/dynamic.rkt

Kind regards, 

Stephen

**Comment by gregid** [comment]
The purpose of this new feature is to enable gathering information required for package statistics. At the moment - new package is equivalent with recently updated package.

**Comment by jeapostrophe** [comment]
Good idea. It will be inaccurate for older packages though.

**Comment by spdegabrielle** [comment]
@jeapostrophe please reopen. I’m hoping to work with @gregid to do a PR

**Comment by gregid** [comment]
@spdegabrielle no need - it has been done already : https://github.com/racket/pkg-index/commit/09fca747882be77e78f12698fb69484241944b37
Thanks @jeapostrophe !

**Comment by spdegabrielle** [comment]
Thanks @gregid !
