### ISSUE TITLE
Static JSON files served from the cache are missing CORS header(s)

### ISSUE THREAD

**Issue by massung** [racket/pkg-index#24]
This makes it impossible to display the version + status of a project from another site. Example end-point: https://pkgd.racket-lang.org/pkgn/pkg/r-cade.json

**Comment by DarrenN** [comment]
Example request:

```
$ curl -i 'https://pkgd.racket-lang.org/pkgn/pkg/r-cade.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive'
```

Response:

```
HTTP/1.1 200 OK
Date: Sun, 23 Feb 2020 16:53:46 GMT
Server: Racket
Last-Modified: Sun, 23 Feb 2020 16:41:28 GMT
Content-Type: application/json
Accept-Ranges: bytes
Content-Length: 1826
Via: 1.1 pkgd.racket-lang.org (Apache/2.4.7)
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

Headers missing `Access-Control-Allow-Origin: *`

**Comment by samth** [comment]
I think this is an S3 configuration issue, the file is served from http://pkgs.racket-lang.org/pkg/r-cade.json which is really http://pkgs.racket-lang.org.s3-website-us-west-2.amazonaws.com/pkg/r-cade.json which also doesn't have CORS headers.

**Comment by massung** [comment]
That would make sense. S3 has support for CORS:

https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors

**Comment by samth** [comment]
I think this should be fixed now -- http://pkgs.racket-lang.org.s3-website-us-west-2.amazonaws.com/pkg/r-cade.json now serves the correct headers. I'm working on the CloudFlare side.

**Comment by massung** [comment]
S3 may be serving the correct headers, but they aren't propagating through pkgd.racket-lang.org yet. Thanks for working on this!

**Comment by samth** [comment]
Ok, the URL https://pkgs.racket-lang.org/pkg/r-cade.json now serves the correct headers. Next step is propagating through the Apache redirect.

**Comment by samth** [comment]
@jeapostrophe @tonyg Any thoughts here? I'm still stuck.

**Comment by jeapostrophe** [comment]
When I look at

https://pkgd.racket-lang.org/pkgn/pkg/r-cade.json
https://pkgs.racket-lang.org/pkg/r-cade.json
http://pkgs.racket-lang.org.s3-website-us-west-2.amazonaws.com/pkg/r-cade.json
https://s3-us-west-2.amazonaws.com/pkgs.racket-lang.org/pkg/r-cade.json

None of them have the `Access-Control-Allow-Origin` header.

In S3, we have the following CORS configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

I'm not sure what's going on, given that there are so many layers of redirection and caching.

**Comment by samth** [comment]
You need to set an `Origin` header in the request. Here's a command line:

````
curl -H "Origin: http://example.com" --verbose https://pkgs.racket-lang.org/pkg/r-cade.json
```

The second, third, and fourth URLs you list all have the appropriate headers with that set.

**Comment by massung** [comment]
> You need to set an Origin header in the request. Here's a command line:

Wanted to note that the browser automatically does this. If I use curl, I do see the CORS headers in the response:

```
< HTTP/2 200 
< date: Sun, 15 Mar 2020 13:22:29 GMT
< content-type: application/json
< content-length: 1900
< set-cookie: __cfduid=d64d355beca06ef073a4df629802fae7b1584278548; expires=Tue, 14-Apr-20 13:22:28 GMT; path=/; domain=.racket-lang.org; HttpOnly; SameSite=Lax
< x-amz-id-2: gPTmDxP4QWTCo/N+wLgxBFsi3RJaxZ31Iu4CwmQX2XG8bItWJLV2RcSlp9Ue7B5JbDiJkKeGPr0=
< x-amz-request-id: DE5B070E5ECD839F
< access-control-allow-origin: *
< access-control-allow-methods: GET
< vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
< last-modified: Sun, 15 Mar 2020 12:36:04 GMT
< etag: "6c27d9f0c5f38b2c12d0b7bad2da5b23"
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 57468b21ce16ea18-IAD
```

But, from the browser they are not present:

![Capture](https://user-images.githubusercontent.com/746946/76702320-e6b57280-6696-11ea-8494-12e757aafaf3.PNG)

That's a screenshot of the network panel in the Chrome debugger. At the bottom are the request headers, and "Origin" is there. Likewise, the response does not have the CORS headers. 

I'm unsure why this discrepancy exists.

**Comment by samth** [comment]
The last image you show is of the pkgd url, which is the one that doesn't have cors headers in my testing.

**Comment by massung** [comment]
Ah, my bad. :smile:

**Comment by jeapostrophe** [comment]
Okay, I updated the apache config. I believe it's good now.

**Comment by massung** [comment]
I can confirm, it's working perfectly! Thank you. Link to see in action: https://r-cade.io/changelog
