### ISSUE TITLE
Remove legacy passwd storage

### ISSUE THREAD

**Issue by tonyg** [racket/pkg-index#3]
There are only eight user accounts left in the legacy password database. I propose that now is a good time to remove all the code from the system to do with legacy password storage, and to delete the legacy password database. If ever those users log in again, they will have to generate a fresh password, but I think that since a) there are only eight such accounts, b) they haven't been used since early 2013, and c) it's not much of an obstacle to reregister anyway, I think the benefit of removing obsolete, security-sensitive code outweighs the disadvantages.

**Comment by rfindler** [comment]
+1
