### ISSUE TITLE
Next package refresh cycle scheduled time shows current time

### ISSUE THREAD

**Issue by countvajhula** [racket/pkg-index#30]
While on the page for a package on the package index, in certain cases (e.g. after editing the package description) it shows a message like this one:

` This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Saturday, August 21st, 2021 9:28:57pm (UTC).`

The time displayed there is actually the current time in UTC (e.g. this was a few minutes ago, 2:28pm PDT), so this doesn't really convey what it intends to.

**Comment by countvajhula** [comment]
Actually, I'm not sure anymore. The message appears to be updated every ten minutes or so to indicate a fresh future time. Right now, it says:

` This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Saturday, August 21st, 2021 9:43:57pm (UTC).`

... but formerly it said `9:38pm` and that time came and went and the message still remained. If the refresh had occurred then, shouldn't the message have disappeared?

**Comment by countvajhula** [comment]
And the message has disappeared. Maybe it takes a couple of cycles to get into the queue? In any case, looks like this is OK so I'm going to close the issue. I initially raised it because I was wondering about when the docs would be rebuilt and assumed this message was supposed to be indicating that. I don't suppose there's a way to see that information anywhere?

**Comment by samth** [comment]
I think what's happening is that at that time, the refresh process starts, but the package isn't marked as up to date, so it gets the new message. Then the process updates the package and the message goes away.

**Comment by countvajhula** [comment]
That makes sense.
