### ISSUE TITLE
Unexpected empty package source for main-distribution

### ISSUE THREAD

**Issue by sorawee** [racket/pkg-index#34]
Go to https://pkgs.racket-lang.org/pkgs-all.json.gz. Pick any package in the main-distribution (e.g. `htdp-lib`). We will see that the `source` and `checksum` are always `http://racket-packages.s3-us-west-2.amazonaws.com/pkgs/empty.zip` and `9f098dddde7f217879070816090c1e8e74d49432` respectively.

<img width="727" alt="Screen Shot 2022-06-07 at 12 24 00 PM" src="https://user-images.githubusercontent.com/9099577/172465274-f7d8e811-c252-4047-9395-dea294a190a6.png">

This causes an issue when I run `pkg-index` locally (with `raco pkg catalog-copy https://pkgs.racket-lang.org pkgs-copy/`), because any computation based on this information (e.g. https://github.com/racket/pkg-index/blob/master/official/update.rkt#L142) will be incorrect. For example, it would update all packages in the main-distribution, resulting in empty `dependencies`.

Two concrete questions/suggestions:
- Where does this `http://racket-packages.s3-us-west-2.amazonaws.com/pkgs/empty.zip` come from?
- Would it be a good idea to workaround the issue by using `(hash-ref (hash-ref (hash-ref i 'versions) 'default) 'source)` (which has correct information) everywhere instead of using `(hash-ref i 'source)`? https://pkgs.racket-lang.org/ essentially does this. That's why the problem doesn't seem to appear on the web interface.

**Comment by sorawee** [comment]
Further investigation: the empty package thingy was handled in `racket-pkg-website` in https://github.com/racket/racket-pkg-website/commit/549908aa2185099d13111b43363b5fa9618f662f by @tonyg

**Comment by sorawee** [comment]
Thanks!

I think I understand now what's going on (correct me if I'm wrong). Packages in the main distribution fake their sources and checksums so that they appear to be an empty package, which is "up-to-date" perpetually. This means `update.rkt` would skip over processing the packages, because `(equal? new-checksum old-checksum)` is true.

This is brittle, however. My PR (#33) will add more fields to each package. In the initial run, it will forcibly update all packages, including those in the main distribution, since none of them has the field yet. This breaks the above protocol.

What's the best way to proceed?

**Comment by sorawee** [comment]
Mystery solved: the source of the whole package is set to the source of version 5.3.6 whenever possible (https://github.com/racket/pkg-index/commit/5f3be74f915c821361c53bd0ca22049b45c5a6d5#diff-6f109a743e6d0d3defc3e2a644b4624628dad9b5ab1b9ec9742a1bf83ccf4cb9R76)

@jeapostrophe, do you recall why you did that, and does that code still make sense now that the Racket version is 8.5?

**Comment by jeapostrophe** [comment]
If I recall correctly, after that version, it will look at the version hash table, but before it won't, so the base data is just for that version and prior
