### ISSUE TITLE
Index refresh message continues forever

### ISSUE THREAD

**Issue by javacommons** [racket/pkg-index#49]
On https://pkgd.racket-lang.org/pkgn/package/access
I got the following message after editing the package description

	This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Thursday, July 18th, 2024 11:11:36pm (UTC).

The time displayed there is actually the current time in UTC (July 18th, 2024 11:11:36pm (UTC)).
It is normal for this message to appear. However, when the time came (July 18th, 2024 11:11:36pm (UTC)), the following message appeared again. Actually, I had not updated the git repository.

	This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Thursday, July 18th, 2024 11:16:36pm (UTC).

This cycle continues forever.

```
This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Thursday, July 18th, 2024 11:11:36pm (UTC).
This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Thursday, July 18th, 2024 11:16:36pm (UTC).
This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Thursday, July 18th, 2024 11:26:36pm (UTC).
This package has been modified since the package index was last rebuilt. The next index refresh is scheduled for Thursday, July 18th, 2024 11:31:36pm (UTC).
.
.
.
```

**Comment by jryans** [comment]
The package index update step has been having a bit of trouble the last few days... I've just restarted the service, and it looks to be doing better now.

I think that may resolve this issue as well, but I'm also not fully confident, so let me know if it seems better to you. 🙂

**Comment by javacommons** [comment]
The problem has gone now.
Thak you for your help.
I'm closing this issue now.
